# Generated by Django 4.2.11 on 2025-05-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_utilisateur', '0001_initial'),
        ('gestion_inventaire', '0002_batiment_equipement_salle_remove_equipment_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100, verbose_name='Sujet')),
                ('duree', models.PositiveIntegerField(verbose_name='Durée (heures)')),
                ('frequence', models.CharField(choices=[('HEBDOMADAIRE', 'Hebdomadaire'), ('UNIQUE', 'Unique')], max_length=20, verbose_name='Fréquence')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='GroupeEtudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('taille', models.PositiveIntegerField(verbose_name='Taille')),
            ],
            options={
                'verbose_name': "Groupe d'étudiants",
                'verbose_name_plural': "Groupes d'étudiants",
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_utilisateur.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(verbose_name='Début')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing_cours.cours', verbose_name='Cours')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inventaire.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing_cours.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='equipements_requis',
            field=models.ManyToManyField(blank=True, to='gestion_inventaire.equipement', verbose_name='Équipements requis'),
        ),
        migrations.AddField(
            model_name='cours',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing_cours.groupeetudiants', verbose_name='Groupe'),
        ),
    ]
