# Generated by Django 4.2.11 on 2025-05-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Salle de cours'), ('AMPHI', 'Amphithéâtre'), ('LAB', 'Laboratoire'), ('OFFICE', 'Bureau'), ('MEETING', 'Salle de réunion')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='gestion_inventaire.building')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('rooms', models.ManyToManyField(blank=True, related_name='equipment', to='gestion_inventaire.room')),
            ],
        ),
    ]
