# Generated by Django 4.2.11 on 2025-05-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_mobile', models.BooleanField(default=False, verbose_name='Est mobile')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('etage', models.IntegerField(verbose_name='Étage')),
                ('type_salle', models.CharField(choices=[('COURS', 'Salle de cours'), ('AMPHI', 'Amphithéâtre'), ('LABO', 'Laboratoire'), ('BUREAU', 'Bureau'), ('REUNION', 'Salle de réunion')], max_length=20, verbose_name='Type de salle')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='gestion_inventaire.batiment', verbose_name='Bâtiment')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='equipement',
            name='salles',
            field=models.ManyToManyField(blank=True, related_name='equipements', to='gestion_inventaire.salle', verbose_name='Salles'),
        ),
    ]
